apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
  labels:
    app: argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
